import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GoogleOAuthProvider } from "@react-oauth/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <GoogleOAuthProvider clientId="98683621565-ktsjs4g7n2grbkh35888dbs5443h9t2b.apps.googleusercontent.com">
            <html lang="en">
                <body className={inter.className}>{children}</body>
            </html>
        </GoogleOAuthProvider>
    );
}
